### PR TITLE
Replaced deprecated «ConfigurationHolder» class to «Holders» for Grails 2.4 compatibility

### PR DESCRIPTION
**Pull request by wwarlock**

### CODE REVIEW

**Comment by antony** [comment]
Thanks for this!

**Comment by wwarlock** [comment]
You are welcome.
Please apply that commit to your sources and publish new version of the plugin.

**Comment by antony** [comment]
Hi,

I will release a new version asap.

Cheers,
Antony

**Comment by wwarlock** [comment]
Thanks a lot

**Comment by antony** [comment]
Hi Wwarlock,

Just a quick update - there is some issue with my credentials for the
grails plugin portal so I can't release the new version at the moment.

I'll let you know as soon as it is resolved.

Cheers,
Antony

On 9 June 2014 11:37, wwarlock notifications@github.com wrote:

> Thanks a lot
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aiten/grails-ajax-uploader/pull/23#issuecomment-45478877
> .

## 

---

ꜽ . antony jones . http://www.enzy.org

**Comment by wwarlock** [comment]
Ok, thanks

**Pull request merged**
